### ISSUE TITLE
Huge server performace dip

### ISSUE THREAD

**Issue by Jeavess** [BlueTree242/DiscordSRVUtils#156] opened 2024-02-07 22:00 UTC
java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
 how do i fix this

**Comment by Jeavess** [comment] 2024-02-07 22:00
[22:58:02 ERROR]: The following error have a high chance to be caused by DiscordSRVUtils. Report at https://discordsrvutils.xyz/support and not discordsrv's Discord.
[22:58:02 WARN]: java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[22:58:02 WARN]: 	at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.bukkit.BukkitDiscordSRV.getDiscordId(BukkitDiscordSRV.java:43)
[22:58:02 WARN]: 	at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.systems.leveling.PlayerStats.handleRewards(PlayerStats.java:151)
[22:58:02 WARN]: 	at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.systems.leveling.PlayerStats.setXP(PlayerStats.java:117)
[22:58:02 WARN]: 	at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.systems.leveling.listeners.game.GameLevelingListener.lambda$onChat$1(GameLevelingListener.java:86)
[22:58:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:58:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:58:02 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:58:02 ERROR]: Read the note above the error Please.
[22:58:02 WARN]: java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[22:58:02 WARN]: 	at InteractiveChatDiscordSrvAddon-4.2.8.0.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents.processGameMessage(OutboundToDiscordEvents.java:586)
[22:58:02 WARN]: 	at InteractiveChatDiscordSrvAddon-4.2.8.0.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents.handleGameToDiscord(OutboundToDiscordEvents.java:206)
[22:58:02 WARN]: 	at InteractiveChatDiscordSrvAddon-4.2.8.0.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents.onGameToDiscordHighest(OutboundToDiscordEvents.java:183)
[22:58:02 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[22:58:02 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:149)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1679)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1615)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.listeners.PlayerChatListener.lambda$onAsyncPlayerChat$0(PlayerChatListener.java:43)
[22:58:02 WARN]: 	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.lambda$runTaskAsynchronously$1(SchedulerUtil.java:95)
[22:58:02 WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[22:58:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:58:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:58:02 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by BlueTree242** [comment] 2024-02-07 22:24
duplicate of #154

**Closed as not planned by BlueTree242** 2024-02-07 22:24 UTC
Labels: bug
